"use client";
import { Activity, ShieldCheck, AlertTriangle } from "lucide-react";

interface ReportProps {
  symptoms: string[];
  results: { disease: string; confidence: number }[];
  date: string;
  engine: string;
}

export default function DiagnosisReportAdv({
  symptoms,
  results,
  date,
  engine,
}: ReportProps) {
  return (
    <div className="bg-white rounded-2xl p-4 md:p-5 border border-indigo-400 shadow-xl max-w-xl mx-auto w-full">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3 mb-4">
        <div>
          <h2 className="text-base md:text-lg font-black text-slate-900 leading-none">
            Diagnosis Report
          </h2>
          <p className="text-slate-400 text-[9px] font-bold uppercase tracking-widest mt-1 flex items-center flex-wrap gap-1">
            {new Date(date).toLocaleDateString("en-GB", {
              day: "2-digit",
              month: "short",
              year: "numeric",
            })}
            <span className="mx-1 w-1 h-1 rounded-full bg-indigo-400 shrink-0" />
            {new Date(date).toLocaleTimeString("en-GB", {
              hour: "2-digit",
              minute: "2-digit",
              hour12: true,
            })}
          </p>
        </div>
        <div className="bg-indigo-50 text-indigo-600 p-2 rounded-xl shrink-0">
          <Activity size={18} />
        </div>
      </div>

      <div className="space-y-4">
        {/* Symptoms Section */}
        <div>
          <h4 className="text-xs font-black text-indigo-600 uppercase tracking-widest mb-3">
            Recorded Symptoms
          </h4>
          <div className="flex flex-wrap gap-2">
            {symptoms.map((s, i) => (
              <span
                key={i}
                className="bg-slate-50/50 text-slate-900/70 px-2 md:px-3 py-1 rounded-lg text-xs md:text-sm font-medium border border-indigo-100"
              >
                {s.replace(/_/g, " ").replace(/\b\w/g, (l) => l.toUpperCase())}
              </span>
            ))}
          </div>
        </div>

        {/* Results Section */}
        <div>
          <h4 className="text-xs font-black text-indigo-600 uppercase tracking-widest mb-3">
            AI Analysis ({engine} engine)
          </h4>
          <div className="space-y-2 md:space-y-3">
            {results.map((r, i) => (
              <div
                key={i}
                className="flex flex-col sm:flex-row sm:items-center justify-between p-3 md:p-4 bg-slate-50 rounded-xl md:rounded-2xl border border-slate-100 gap-2"
              >
                <span className="font-bold text-slate-800 text-sm truncate flex-1">{r.disease}</span>
                <div className="flex items-center gap-2 w-full sm:w-auto">
                  <div className="flex-1 sm:w-24 h-2 bg-slate-200 rounded-full overflow-hidden">
                    <div
                      className="h-full bg-indigo-400"
                      style={{ width: `${r.confidence}%` }}
                    />
                  </div>
                  <span className="text-sm font-black text-indigo-600 w-10 text-right shrink-0">
                    {r.confidence}%
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Footer Disclaimer */}
        <div className="mt-4 p-3 md:p-4 bg-indigo-50 rounded-xl md:rounded-2xl border border-indigo-100 flex gap-2 md:gap-3">
          <AlertTriangle className="text-indigo-600 shrink-0 mt-0.5" size={18} />
          <p className="text-[10px] md:text-xs text-indigo-800 leading-relaxed">
            This report was generated by the {engine} AI model. Please consult a
            qualified medical professional before taking further steps.
          </p>
        </div>
      </div>
    </div>
  );
}
