"use client";
import { Activity, ShieldCheck, AlertTriangle } from "lucide-react";

interface ReportProps {
  symptoms: string[];
  results: { disease: string; confidence: number }[];
  date: string;
  engine: string;
}

export default function DiagnosisReport({
  symptoms,
  results,
  date,
  engine,
}: ReportProps) {
  return (
    // NEW COMPACT HEADER
    <div className="bg-white rounded-2xl p-5 border border-amber-400 shadow-xl max-w-xl mx-auto">
      <div className="flex justify-between items-center mb-4">
        <div>
          <h2 className="text-lg font-black text-slate-900 leading-none">
            Diagnosis Report
          </h2>
          <p className="text-slate-400 text-[9px] font-bold uppercase tracking-widest mt-1 flex items-center">
            {new Date(date).toLocaleDateString("en-GB", {
              day: "2-digit",
              month: "short",
              year: "numeric",
            })}
            <span className="mx-2 w-1 h-1 rounded-full bg-amber-400 shrink-0" />
            {new Date(date).toLocaleTimeString("en-GB", {
              hour: "2-digit",
              minute: "2-digit",
              hour12: true,
            })}
          </p>
        </div>
        <div className="bg-amber-50 text-amber-600 p-2 rounded-xl shrink-0">
          <Activity size={18} />
        </div>
      </div>

      <div className="space-y-4">
        {/* Symptoms Section */}
        <div>
          <h4 className="text-xs font-black text-amber-600 uppercase tracking-widest mb-3">
            Recorded Symptoms
          </h4>
          <div className="flex flex-wrap gap-2">
            {symptoms.map((s, i) => (
              <span
                key={i}
                className="bg-slate-50/50 text-slate-900/70 px-3 py-1 rounded-lg text-sm font-medium border border-amber-100"
              >
                {s.replace(/_/g, " ").replace(/\b\w/g, (l) => l.toUpperCase())}
              </span>
            ))}
          </div>
        </div>

        {/* Results Section */}
        <div>
          <h4 className="text-xs font-black text-amber-600 uppercase tracking-widest mb-3">
            AI Analysis ({engine} engine)
          </h4>
          <div className="space-y-3">
            {results.map((r, i) => (
              <div
                key={i}
                className="flex items-center justify-between p-4 bg-slate-50 rounded-2xl border border-slate-100"
              >
                <span className="font-bold text-slate-800">{r.disease}</span>
                <div className="flex items-center gap-2">
                  <div className="w-24 h-2 bg-slate-200 rounded-full overflow-hidden">
                    <div
                      className="h-full bg-amber-400"
                      style={{ width: `${r.confidence}%` }}
                    />
                  </div>
                  <span className="text-sm font-black text-amber-600 w-10">
                    {r.confidence}%
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Footer Disclaimer */}
        <div className="mt-4 p-4 bg-amber-50 rounded-2xl border border-amber-100 flex gap-3">
          <AlertTriangle className="text-amber-600 shrink-0" size={20} />
          <p className="text-xs text-amber-800 leading-relaxed">
            This report was generated by the {engine} AI model. Please consult a
            qualified medical professional before taking further steps.
          </p>
        </div>
      </div>
    </div>
  );
}
